### ISSUE TITLE
CSS spacing differences

### ISSUE THREAD

**Issue by dreamwhisper** [copyblogger/genesis-simple-faq#21]
With Nick's fix on #17, I can display the category.

However, there's a difference in display between individual FAQs and Categories.

Category:
![category](https://user-images.githubusercontent.com/1271053/28884032-651a4c14-777e-11e7-8938-b7bd12b17be6.png)

Individual FAQ:
![individual faq in a row](https://user-images.githubusercontent.com/1271053/28884036-66bae150-777e-11e7-8d69-6efb6faed8b2.png)

Looks like reducing the CSS here would allow them to show the same:

```css
.gs-faq__question {
	display: block;
	margin-top: 10px; 
	text-align: left;
	width: 100%;
}
```
