### ISSUE TITLE
Fix button so text will wrap

### ISSUE THREAD

**Issue by dreamwhisper** [copyblogger/genesis-simple-faq#24]
Text can be cutoff

![button](https://user-images.githubusercontent.com/1271053/28983210-b44018ec-7926-11e7-98fe-fc9211362e32.png)

```css
.gs-faq__question {
	display: block;
	margin-top: 10px;
	text-align: left;
	white-space: normal; <-----add
	width: 100%;
}
```

Our internal themes won't have this issue since we do this by default on buttons, but I was testing on a third-party theme.
